### ISSUE TITLE
Warp Layer Tests

### ISSUE THREAD

**Issue by reSHARMA** [NJACKWinterOfCode/synfig-tests-regressions#1]
_From @morevnaproject on November 18, 2018 8:23_

Add tests for Warp Layer (https://wiki.synfig.org/Warp_Layer) to ```sources/layers/warp```.

We need to test following configurations:

1. Warp Layer on top of Checkerboard Layer (https://wiki.synfig.org/Checkerboard_Layer, representing single-point perspective. Like this: 

![screenshot_002](https://user-images.githubusercontent.com/332868/48670118-d04fe300-eb44-11e8-8d63-67fda0428a15.png)

(notice two edges of distortion box are parallel)

2. Warp Layer on top of Checkerboard Layer (https://wiki.synfig.org/Checkerboard_Layer, representing two-point perspective. Like this: 

![screenshot_003](https://user-images.githubusercontent.com/332868/48670120-dba30e80-eb44-11e8-9056-35b24ff46b2b.png)

Both configurations should be represented with the following parameter variations:

* Clip: 
   * on (default)
   * off
* Horizon:
   * 2.0
   * 4.0

It is expected to have filenames like this:

* **warp-checkerboard-1point-horizon-2.sif** - single-point perspective with Clip=on (default) and Horizon = 2.0
* **warp-checkerboard-1point-horizon-4.sif** - single-point perspective with Clip=on and Horizon = 4.0
* **warp-checkerboard-1point-noclip-horizon-2.sif** - single-point perspective with Clip=off and Horizon = 2.0
* **warp-checkerboard-1point-noclip-horizon-4.sif** - ...
* **warp-checkerboard-2point-horizon-2.sif** - two-point perspective with Clip=on and Horizon = 2.0
* **warp-checkerboard-2point-horizon-4.sif** - ...
* **warp-checkerboard-2point-noclip-horizon-2.sif** - ...
* **warp-checkerboard-2point-noclip-horizon-4.sif** - ...

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

_Copied from original issue: synfig/synfig-tests-regressions#14_

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject 
That would be helpful If i can get the exact values for the following
![screenshot from 2019-01-04 22-03-22](https://user-images.githubusercontent.com/37617951/50699439-e28ecd80-106d-11e9-8031-056df30ad8f3.png)

 as I don't think its a good idea to drag drop and make my image look somewhat similar in the comment above. :sweat_smile:

**Comment by morevnaproject** [comment]
Um, sorry I didn't understood the question. Can you elaborate, please? ^__^"

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I'm just not able to get the exact same result as the image shown there. 
See my edited comment.

**Comment by morevnaproject** [comment]
I see now! I hope you don't mind if instead I will show you creation process for those two samples ^__^ - 
https://www.youtube.com/watch?v=UGJhIbLrqk0
You can achieve the same by repeating steps on the video.

**Comment by ankit-kumar-dwivedi** [comment]
That's great. So now I solved the last issue. :smiley:

**Comment by morevnaproject** [comment]
Great! I am waiting for PR. ^__^

**Comment by morevnaproject** [comment]
Congratulations for solving last issue! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> Congratulations for solving last issue! ^__^

perhaps you can add more issues :)

**Comment by morevnaproject** [comment]
Sorry, I haven't managed to prepare other issues yet, will do that soon! Thank you! ^__^
