### ISSUE TITLE
Include synfig studio's icons files to our test suite

### ISSUE THREAD

**Issue by reSHARMA** [NJACKWinterOfCode/synfig-tests-regressions#10]
_From @reSHARMA on November 21, 2018 9:55_

Synfig studio's icon files are updated at https://github.com/synfig/synfig/tree/master/synfig-studio/images.

A bash script that would automatically update them from latest commit of Synfig's official repository.

We will run this script from time to time to sync icons in https://github.com/synfig/synfig-tests-regressions with icon files in https://github.com/synfig/synfig

_Copied from original issue: synfig/synfig-tests-regressions#23_

**Comment by ankit-kumar-dwivedi** [comment]
Can you please explain what exactly you want? As I see https://github.com/synfig/synfig/tree/master/synfig-studio/images contain .sif images but where should it be synced?
Also, https://github.com/synfig/synfig-test-regressions gives 404.

**Comment by morevnaproject** [comment]
> Can you please explain what exactly you want? As I see https://github.com/synfig/synfig/tree/master/synfig-studio/images contain .sif images but where should it be synced?

We expect a simple bash script (you can place it in the root of this repository).
The script will download  latest snapshot of https://github.com/synfig/synfig (I think ZIP snapshot will be more efficient than full git repo). Then it will unpack snapshot in some temporary directory and copy all .sif files from "synfig-studio/images/" to this repository (I suggest to place them to "sources/icons").

So, expected workflow is following:
- User fetches this repository (synfig-tests-regressions).
- He runs script.
- Script updates files at "sources/icons" in user's working copy and commits changes.

> Also, https://github.com/synfig/synfig-test-regressions gives 404

Sorry, there is a typo. Should be https://github.com/synfig/synfig-tests-regressions
Fixed now.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I wish to use svn as this answer says "https://stackoverflow.com/a/18194523" will place the script file in the repository :)
