### ISSUE TITLE
Convert sifz to sif

### ISSUE THREAD

**Issue by reSHARMA** [NJACKWinterOfCode/synfig-tests-regressions#11]
_From @reSHARMA on November 21, 2018 9:59_

Include complex examples from https://github.com/synfig/synfig/tree/master/synfig-core/examples

They are saved as "sifz" files, so the task would be to re-save them all to "sif". Possibly, through a script which turns all sifz files to sif.

_Copied from original issue: synfig/synfig-tests-regressions#24_

**Comment by ankit-kumar-dwivedi** [comment]
Examples after unzip should replace the one at https://github.com/synfig/synfig/tree/master/synfig-core/examples or should I include them in this repository?

**Comment by morevnaproject** [comment]
Please include them into this repository. We expect them to be placed in "sources/examples" subdirectory of this repository.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I am getting warnings when I open the files. 

**Should I ignore the warning!**
![image](https://i.imgur.com/5d3JcHb.png)

So I thought I can simple unzip them using gzip but I found I can't :/

**Comment by ankit-kumar-dwivedi** [comment]
Added the files.
@morevnaproject can I join synfig org?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Thank you!

> can I join synfig org?

Do you mean you would like to contribute to Synfig's code? ^__^

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Please let me know what you mean "join synfig org". We are always welcome new contributors! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> @ankit-kumar-dwivedi Please let me know what you mean "join synfig org". We are always welcome new contributors! ^__^

That's great ! What communication channel do synfig use ? Gitter or slack?

**Comment by morevnaproject** [comment]
We do not use real-time communication channels. Development-specific communication mainly happens on GitHub here - https://github.com/synfig/synfig/issues
You can ping main developers - @blackwarthog, @ice0 and me (@morevnaproject).

We have a special list of easy issues that are easy to get started - https://github.com/synfig/synfig/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

For more general questions you can communicate via forums - https://forums.synfig.org/
