### ISSUE TITLE
Fix CI script

### ISSUE THREAD

**Issue by morevnaproject** [NJACKWinterOfCode/synfig-tests-regressions#18]
This repository (https://github.com/synfig/synfig-tests-regressions) have CI automation configured.

Every time when someone pushes commit, Travis CI runs "render.sh" script (located in the root of repository). The command is "render.sh references" - see it in https://github.com/synfig/synfig-tests-regressions/blob/master/.travis.yml

The "render.sh" script  checks for changed files and renders source files located in "sources/" directory to png files in "references/".

Problem: the "render.sh" script is not renders files from latest commits. You can see build log here - https://travis-ci.org/synfig/synfig-tests-regressions/builds/468261296

Note the error lines like:
```
Target name = png
Outfilename = /home/travis/build/synfig/synfig-tests-regressions/sources/../references/layers/gradient-curve/gradient-curve-shape2-width-0.png
boost::filesystem::canonical: No such file or directory: "/home/travis/build/synfig/synfig-tests-regressions/sources/../references/layers/gradient-curve"
```

This needs fixing.

---
Issue copied from https://github.com/synfig/synfig-tests-regressions/issues/25

**Comment by ankit-kumar-dwivedi** [comment]
will work on it 😀

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject is the error already fixed? I see the build log is passing.
:christmas_tree: :christmas_tree: merry christmas :smiley:

**Comment by morevnaproject** [comment]
@morevnaproject The build log indicates build as successful, but there are still errors in the log:
```
Target name = png
Outfilename = /home/travis/build/synfig/synfig-tests-regressions/sources/../references/layers/gradient-curve/gradient-curve-shape2-width-0.png
boost::filesystem::canonical: No such file or directory: "/home/travis/build/synfig/synfig-tests-regressions/sources/../references/layers/gradient-curve"
```
And, as result, the files in "references/" directory are not generated from files "sources/" directory.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I tried searching about the error but could not find stuff related to travis CI on this error. Also as I have zero expertise on Travis Integration that would be a great help if you can give me a hint!
PS: sorry for the delay was enjoying the break after exams. Death note made me so involved I never realized it cost 2 days!!

**Comment by morevnaproject** [comment]
Apologies  for delay, your comment made me re-watch Death Note and indeed it took 2 days. XD
I hope you're also having a great end-of-year holidays!

> According to what I see there is some check needed in order to create the directory where files are to be stored after rendering if the directory is not already there.

Yes, exactly!

in ```https://github.com/synfig/synfig-tests-regressions/blob/master/.travis.yml``` on line 5 you can see that Travis is executing ```render.sh``` script:

https://github.com/synfig/synfig-tests-regressions/blob/58219da55ab2572e03dad326cb05ac97699d953f/.travis.yml#L5

So, the ```render.sh``` script is executed and it fails to render some tests, because target directories are missing. We need a fix for a script, which makes sure that all directories are created.

Happy New Year! :christmas_tree:

**Comment by morevnaproject** [comment]
P.S. Link to ```render.sh``` script - https://github.com/synfig/synfig-tests-regressions/blob/58219da55ab2572e03dad326cb05ac97699d953f/render.sh

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject 
> Happy New Year! christmas_tree
Same to you !

Any way I can test my fix (by running it?)?
I think [this](https://github.com/synfig/synfig-tests-regressions/blob/58219da55ab2572e03dad326cb05ac97699d953f/render.sh#L124) is where the problem lies.

**Comment by morevnaproject** [comment]
> Any way I can test my fix (by running it?)?

If you have a Linux machine, then you can test it locally. Just run "render.sh" script.
I t will take some time depending on internet connection, because it is downloads appropriate version of Synfig before making tests.

While the script runs watch for error lines containing "boost::filesystem::canonical:".

**Comment by morevnaproject** [comment]
Oh, and one more thing. Currently the script doesn't stops if it hits an error. But if you add ```set -e``` line in the beginning (right after ```#set -x``` line), then it will stop when it encounters an error. That would make debugging easier. ^__^

**Comment by morevnaproject** [comment]
Ah, sorry, scratch my previous comment. Adding "set -e" doesn't makes the script stop when synfig throws "boost::filesystem::canonical:" error. This is actually issue of synfig - it should return non-zero exit code, to make it treated as error.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject should the files be rendered in sources? and not references?

**Comment by morevnaproject** [comment]
Awesome, thank you! ^__^
