### ISSUE TITLE
Linear Gradient Tests

### ISSUE THREAD

**Issue by reSHARMA** [NJACKWinterOfCode/synfig-tests-regressions#2]
_From @morevnaproject on November 18, 2018 9:32_

Add tests for Linear Gradient Layer (https://wiki.synfig.org/Linear_Gradient_Layer) to ```sources/layers/gradient-linear```.

We need several tests with some key color combinations:
```
gradient-linear-black-white.sif
gradient-linear-blue-yellow.sif
gradient-linear-blue-black.sif
gradient-linear-blue-white.sif
gradient-linear-red-black.sif
gradient-linear-red-white.sif
gradient-linear-red-alpha.sif
```

And also some tests for "Loop" and "ZigZag" parameters (and their combinations):

```
gradient-linear-black-white-loop.sif
gradient-linear-black-white-zigzag.sif
gradient-linear-black-white-loop-zigzag.sif
```

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

_Copied from original issue: synfig/synfig-tests-regressions#15_

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject added the PR 
can you add any intermediate/difficult tasks?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Awesome!

> can you add any intermediate/difficult tasks?

I will try to come up with something soon. ^__^

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Here goes one more intermediate issue - https://github.com/NJACKWinterOfCode/synfig-tests-regressions/issues/18
