### ISSUE TITLE
Prettify README

### ISSUE THREAD

**Issue by saurabhshadow** [NJACKWinterOfCode/synfig-tests-regressions#21]

**Comment by morevnaproject** [comment]
Can you please describe what do you mean by this issue in detail?

**Comment by saurabhshadow** [comment]
make it look more user-friendly & should look good!

**Comment by morevnaproject** [comment]
Okay, I am looking forward for a pull request, which is addressing your issue. ^__^

**Comment by morevnaproject** [comment]
Hello! The pull #22 is merged now. ^__^
I have noticed the link at the bottom does not parsed for some reason -
![screenshot_001](https://user-images.githubusercontent.com/332868/50561645-354f4900-0d3f-11e9-8169-4c8cbc58e2c5.png)
Can you please fix this?

Alternatively, we can remove the link. ^__^

Also, can you please replace "Konstantin Dmitriev" to "Synfig contributors? ^__^

Happy New Year!

**Comment by morevnaproject** [comment]
Solved by PR #22 and #23
