### ISSUE TITLE
fetch-icon.sh needs a fix

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [NJACKWinterOfCode/synfig-tests-regressions#24]
the line https://github.com/NJACKWinterOfCode/synfig-tests-regressions/blob/43a6e1891f0dda11d301e228450192e93bf0ac53/fetch-icon.sh#L34
is there 2 times should be only once
PS: in my local version i can see it's only written once

**Comment by morevnaproject** [comment]
Hmm, you right, for some reason we have this line twice. Probably I did merge inaccurately somehow. Can you make a fix, please? ^__^
