### ISSUE TITLE
Noise Gradient Layer Tests

### ISSUE THREAD

**Issue by reSHARMA** [NJACKWinterOfCode/synfig-tests-regressions#7]
_From @reSHARMA on November 21, 2018 9:34_

Add tests for Noise Gradient Layer (https://wiki.synfig.org/Noise_Gradient_Layer) to sources/layers/noise-gradient.

We expect to see :)

gradient-noise-black-white.sif
gradient-noise-blue-yellow.sif
gradient-noise-blue-black.sif
gradient-noise-blue-white.sif
gradient-noise-red-black.sif
gradient-noise-red-white.sif
gradient-noise-red-alpha.sif
gradient-noise-black-white-size-0-0.sif
gradient-noise-black-white-size-1-1.sif
gradient-noise-black-white-size-1-60.sif
gradient-noise-black-white-size-60-1.sif
gradient-noise-black-white-size-5-200.sif
gradient-noise-black-white-size-200-5.sif
gradient-noise-black-white-size-20-20.sif
gradient-noise-black-white-size-200-200.sif
gradient-noise-black-white-interpolation-nearestneighbor.sif
gradient-noise-black-white-interpolation-linear.sif
gradient-noise-black-white-interpolation-cosine.sif
gradient-noise-black-white-interpolation-spline.sif
gradient-noise-black-white-interpolation-cubuc.sif
gradient-noise-black-white-detail-0.sif
gradient-noise-black-white-detail-1.sif
gradient-noise-black-white-detail-2.sif
gradient-noise-black-white-detail-3.sif
gradient-noise-black-white-detail-10.sif
gradient-noise-black-white-turbulent.sif
gradient-noise-black-white-doalpha.sif
gradient-noise-black-white-supersample.sif

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

_Copied from original issue: synfig/synfig-tests-regressions#20_

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject 
what is **center** in
>  gradient-noise-black-white-center-20-20.sif

**Comment by ankit-kumar-dwivedi** [comment]
Just googled your name out of curiosity and got to know more about you. That's great how you can code sketch and manage so much things at the same time. You must be always busy? how you find time for yourself?
Maybe GitHub is not right place to talk all this :smile:

**Comment by morevnaproject** [comment]
> what is center in
>>    gradient-noise-black-white-center-20-20.sif

Oh, this is added by mistake. Please ignore this line. ^__^

**Comment by morevnaproject** [comment]
> PS: I today saw that, i can save the filename containing leading whitespaces however this is not a good thing and should be handled by synfig while saving the new file.

I think this behavior is OK. I have examined how this handled in other graphic software (namely - in Gimp and Krita) - they also allow spaces in beginning of filename.

**Comment by morevnaproject** [comment]
> That's great how you can code sketch and manage so much things at the same time. You must be always busy? how you find time for yourself?

I just doing things that I love, and I love that feeling to be able to change something, together with many other awesome people. Yes, I almost always busy, but the things I do make me happy. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> 
> I think this behavior is OK. I have examined how this handled in other graphic software (namely - in Gimp and Krita) - they also allow spaces in beginning of filename.

Oh that's fine then.

> I just doing things that I love, and I love that feeling to be able to change something, together with many other awesome people. Yes, I almost always busy, but the things I do make me happy. ^__^

That's great I just read your [interview](http://www.ocsmag.com/2015/06/11/synfig-studio-an-interview-with-konstantin-dmitriev/) from 2015 that's inspiring how you kept working despite of whatever challenges came around. 
I think many people must have given suggestion to you but I think we can certainly improve the quality participation in synfig by taking it to platforms like GSOC, Girlscript SOC and similar programs.
 I saw the project is listed on KSOC and NjackWinterofCode and that's good for a start but to make it more beginner friendly 

- there should be some discussion forum 
- and quick start guide for beginners.

Well if you would ask me why I considered this project..... this is because I wanted to contribute to something artistic and something that interest me. As the program ends on 6th jan I might say it was a great experience for me and will keep contributing. :smile:

**Comment by morevnaproject** [comment]
> That's great I just read your interview from 2015 that's inspiring how you kept working despite of whatever challenges came around.

Oh, that's a blast from the past! Thank you for reminding me about this article - it is really fun to take a look back  to see how  things were a few years ago. ^__^

> I think many people must have given suggestion to you but I think we can certainly improve the quality participation in synfig by taking it to platforms like GSOC, Girlscript SOC and similar programs.

Yeah, we plan to apply for GSoC this year ^__^ - https://github.com/synfig/synfig/issues/499

Thank you for note about Girlscript SOC - I wasn't aware about it.. Added to my notes. ^__^

> there should be some discussion forum

There is! ^__^ - https://forums.synfig.org/ 
Also, recently we did a major update of forums engine and there are plans for more. ^__^ - https://www.synfig.org/2018/08/04/forums-migrated-to-discourse/

> and quick start guide for beginners.

Yes, the dev documentation is a kind of mess and mostly outdated.
But we are working on improving! Here is a quick start for building Synfig - https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html
There is also a positive dynamics recently - @BobSynfg writes tutorials on how he does his changes to Synfig code. Here:
- https://wiki.synfig.org/Dev:Adding_a_Sound_notification
- https://wiki.synfig.org/Dev:Adding_a_Render_progress_bar

> Well if you would ask me why I considered this project..... this is because I wanted to contribute to something artistic and something that interest me. As the program ends on 6th jan I might say it was a great experience for me and will keep contributing. :smile:

Awesome! It is my pleasure to work with you! ^__^
