### ISSUE TITLE
Spiral Gradient Layer

### ISSUE THREAD

**Issue by reSHARMA** [NJACKWinterOfCode/synfig-tests-regressions#9]
_From @reSHARMA on November 21, 2018 9:44_

Add tests for Spiral Gradient Layer (https://wiki.synfig.org/Spiral_Gradient_Layer) to sources/layers/spiral-gradient.

We expect to see :)

gradient-spiral-black-white.sif
gradient-spiral-blue-yellow.sif
gradient-spiral-blue-black.sif
gradient-spiral-blue-white.sif
gradient-spiral-red-black.sif
gradient-spiral-red-white.sif
gradient-spiral-red-alpha.sif

Thanks to @ankit-kumar-dwivedi for pointing the wrong samples from radial gradient, I've added some more easy samples for this layer (with changing angle, center and radius ;)

gradient-spiral-black-white-angle-30.sif
gradient-spiral-black-white-center-20-20.sif
gradient-spiral-black-white-radius-0.sif
gradient-spiral-black-white-radius-1.sif
gradient-spiral-black-white-radius-5.sif
gradient-spiral-black-white-radius-20.sif
gradient-spiral-black-white-radius-60.sif
gradient-spiral-black-white-radius-1000.sif
gradient-spiral-black-white-clockwise.sif

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

_Copied from original issue: synfig/synfig-tests-regressions#22_

**Comment by ankit-kumar-dwivedi** [comment]
Can this isuue be assigned to me?
Also I have to send the  PR on this repo or the original [synfig-tests-regressions](https://github.com/synfig/synfig-tests-regressions)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Great, his issue is yours now!
Please submit PR to this repo. ^__^

**Comment by morevnaproject** [comment]
Please check instructions here - https://github.com/NJACKWinterOfCode/synfig-tests-regressions/blob/master/Contributing.md

**Comment by ankit-kumar-dwivedi** [comment]
there is no zig-zig, loop for spiral layer :p @reSHARMA  I guess you copied the same comment

**Comment by reSHARMA** [comment]
@ankit-kumar-dwivedi Ah, sorry I mixed it with Radial Gradient Layer. I'll fix it in the description. Thanks!
